language: cpp
sudo: required
dist: bionic
compiler:
- clang
matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-bionic-7
          packages:
            - clang-7
            - fglrx
            - opencl-headers
      env:
        - COMPILER=clang++-7
    - os: osx
      osx_image: xcode10.1
      env:
        - COMPILER=clang++

before_install:
    - eval "${MATRIX_EVAL}"
    - make clean
script:
    - make all
after_success:
    - ./bin/clunittest
    - ./bin/clBitCrack 173M3yw1P1SfiPiDHABLGi5LLBAMohVQ7h
