language: cpp
sudo: required
compiler:
- clang
matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      dist: bionic
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-bionic-7
          packages:
            - clang-7
            - ocl-icd-opencl-dev
            - opencl-headers
            - lcov
      env:
        - COMPILER=clang++-7
    - os: osx
      osx_image: xcode10.1
      env:
        - COMPILER=clang++

before_install:
    - eval "${MATRIX_EVAL}"
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get update                         ; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install -qy ocl-icd-opencl-dev ; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install -qy opencl-headers     ; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install -qy lcov               ; fi
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update                                   ; fi
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install lcov                             ; fi
    - BUILD_DEBUG=1 make clean
script:
    - BUILD_COVERAGE=1 make all
after_success:
    # Run test
    - ./bin/clunittest
    # Creating report
    - cd ${TRAVIS_BUILD_DIR}
    - lcov --directory . --capture --output-file coverage.info
    - lcov --remove coverage.info '/usr/*' --output-file coverage.info
    - lcov --list coverage.info
    # Uploading report to CodeCov
    - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"