language: cpp
sudo: required
dist: bionic
compiler: clang
matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-7
          packages:
            - clang-7
      env:
        - MATRIX_EVAL="CC=clang-7 && CXX=clang++-7"

    - os: osx
      osx_image: xcode10.1
      env:
        - MATRIX_EVAL=""

before_install:
    - eval "${MATRIX_EVAL}"
    - make clean
script:
    - make all
after_success:
    - ./bin/clunittest
