version: 1.0.{build}

image: Visual Studio 2019

skip_commits:
  # Builds just testing something on Travis CI don't need to be
  # done on AppVeyor
  message: /\[Travis\]|\[AppVeyor\]|\[LGTM\]|\[GitPod\]|\[CodeCov\]/
  # Dont build, if only documentation or was changed
  files:
    - '**/*.md'
    - '**/*.yml'
only_commits:
  message: /build/

environment:
  matrix:
    - PLATFORM: x64
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019

configuration:
  - Release

before_build:
  - if "%PLATFORM%" == "x64" appveyor DownloadFile https://developer.nvidia.com/compute/cuda/10.1/Prod/local_installers/cuda_10.1.105_418.96_win10.exe -FileName cuda_10.1.105_418.96_win10.exe
  - if "%PLATFORM%" == "x64" cuda_10.1.105_418.96_win10.exe -s nvcc_10.1 cudart_10.1 curand_10.1 curand_dev_10.1 npp_10.1 npp_dev_10.1 nvml_dev_10.1 nvrtc_10.1 nvrtc_dev_10.1 visual_studio_integration_10.1
  - if "%PLATFORM%" == "x64" set PATH=%ProgramFiles%\NVIDIA GPU Computing Toolkit\CUDA\v10.1\bin;%PATH%
  - if "%PLATFORM%" == "x64" set CUDA_PATH=%ProgramFiles%\NVIDIA GPU Computing Toolkit\CUDA\v10.1
  - echo %PLATFORM%
  - echo %CONFIGURATION%
  - echo %CUDA_PATH%
 
build:
  verbosity: detailed
  project: $(APPVEYOR_BUILD_FOLDER)\BitCrack.sln